# Generated by Django 5.2 on 2025-04-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='status',
        ),
        migrations.AddField(
            model_name='problem',
            name='hasCompleted',
            field=models.BooleanField(default=False),
        ),
    ]
