# Generated by Django 5.2 on 2025-04-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_remove_problem_status_problem_hascompleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='revisionschedule',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
