# Generated by Django 5.2 on 2025-04-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_problem_user_revisionschedule_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='revisionschedule',
            name='long_notes',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='revisionschedule',
            name='short_notes',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
