# Generated by Django 5.2 on 2025-04-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_revisionschedule_long_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revisionschedule',
            name='long_notes',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='revisionschedule',
            name='short_notes',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
