# Generated by Django 5.2 on 2025-04-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0007_dailyrevision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrevision',
            name='last_revised_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
