# Generated by Django 5.2 on 2025-04-08 14:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0008_alter_dailyrevision_last_revised_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Medium', max_length=50),
        ),
        migrations.AddField(
            model_name='problem',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='dailyrevision',
            name='last_revised_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
